// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_rpJefGTuoVMTlG90RrzV2Fa35WdSLL4',
    appId: '1:1000645777:web:c76d8034bf4c5c06f74b30',
    messagingSenderId: '1000645777',
    projectId: 'wander-hub',
    authDomain: 'wander-hub.firebaseapp.com',
    storageBucket: 'wander-hub.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEx4BDLJ9r0U6uRHdQtbW_fUJPOLSvf_Q',
    appId: '1:1000645777:android:2cfdcefa59c5cca2f74b30',
    messagingSenderId: '1000645777',
    projectId: 'wander-hub',
    storageBucket: 'wander-hub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHlsDhDtNr7HUD92lfXmqWA1DsjQdzo9M',
    appId: '1:1000645777:ios:88559b6fd2f022b7f74b30',
    messagingSenderId: '1000645777',
    projectId: 'wander-hub',
    storageBucket: 'wander-hub.appspot.com',
    iosClientId: '1000645777-pk7jcag94fvf5bnnuovoaneqsnaomk4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.wanderHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHlsDhDtNr7HUD92lfXmqWA1DsjQdzo9M',
    appId: '1:1000645777:ios:88559b6fd2f022b7f74b30',
    messagingSenderId: '1000645777',
    projectId: 'wander-hub',
    storageBucket: 'wander-hub.appspot.com',
    iosClientId: '1000645777-pk7jcag94fvf5bnnuovoaneqsnaomk4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.wanderHub',
  );
}
